t-polardb-x-xtrabackup-opensource:
  machine:
    docker:
      alios7:
        x86_64: hub.docker.alibaba-inc.com/aone-base-global/polardbx_engine:20231214191943
        aarch64: hub.docker.alibaba-inc.com/aone-base-global/polardbx_engine:20231214191943-arm
